# Generated by Django 5.0.1 on 2024-02-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Packages2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Packages3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Packages_1_exterior_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(db_index=True, default='', max_length=100)),
                ('price', models.IntegerField(db_index=True, default=0)),
                ('package_description', models.TextField(db_index=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Packages_1_interior_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(db_index=True, default='', max_length=100)),
                ('price', models.IntegerField(db_index=True, default=0)),
                ('package_description', models.TextField(db_index=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Packages_2_exterior_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(db_index=True, default='', max_length=100)),
                ('price', models.IntegerField(db_index=True, default=0)),
                ('package_description', models.TextField(db_index=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Packages_2_interior_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(db_index=True, default='', max_length=100)),
                ('price', models.IntegerField(db_index=True, default=0)),
                ('package_description', models.TextField(db_index=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Packages_3_exterior_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(db_index=True, default='', max_length=100)),
                ('price', models.IntegerField(db_index=True, default=0)),
                ('package_description', models.TextField(db_index=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Packages_3_interior_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(db_index=True, default='', max_length=100)),
                ('price', models.IntegerField(db_index=True, default=0)),
                ('package_description', models.TextField(db_index=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, default='', max_length=100)),
                ('last_name', models.CharField(db_index=True, default='', max_length=100)),
                ('street_no', models.CharField(db_index=True, default='', max_length=200)),
                ('postal_code', models.CharField(db_index=True, default='', max_length=50)),
                ('city', models.CharField(db_index=True, default='', max_length=100)),
                ('state', models.CharField(db_index=True, default='', max_length=100)),
                ('country', models.CharField(db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_one', models.ManyToManyField(related_name='level_one', to='core1.packages1')),
                ('level_two', models.ManyToManyField(related_name='level_two', to='core1.packages2')),
                ('level_three', models.ManyToManyField(related_name='level_three', to='core1.packages3')),
            ],
        ),
        migrations.AddField(
            model_name='packages1',
            name='exterior_package',
            field=models.ManyToManyField(related_name='level_one_exterior_package', to='core1.packages_1_exterior_data'),
        ),
        migrations.AddField(
            model_name='packages1',
            name='interior_package',
            field=models.ManyToManyField(related_name='level_one_interior_package', to='core1.packages_1_interior_data'),
        ),
        migrations.AddField(
            model_name='packages2',
            name='exterior_package',
            field=models.ManyToManyField(related_name='level_two_exterior_package', to='core1.packages_2_exterior_data'),
        ),
        migrations.AddField(
            model_name='packages2',
            name='interior_package',
            field=models.ManyToManyField(related_name='level_two_interior_package', to='core1.packages_2_interior_data'),
        ),
        migrations.AddField(
            model_name='packages3',
            name='exterior_package',
            field=models.ManyToManyField(related_name='level_three_exterior_package', to='core1.packages_3_exterior_data'),
        ),
        migrations.AddField(
            model_name='packages3',
            name='interior_package',
            field=models.ManyToManyField(related_name='level_three_interior_package', to='core1.packages_3_interior_data'),
        ),
    ]
