# Generated by Django 5.0.1 on 2024-02-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0002_packages_1_extra_data_packages_2_extra_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(db_index=True, default='', max_length=100)),
                ('price', models.IntegerField(db_index=True, default=0)),
                ('package_description', models.TextField(db_index=True, default='')),
                ('level', models.CharField(choices=[('level_one', 'Level One'), ('level_two', 'Level Two'), ('level_three', 'Level Three')], db_index=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='packages1',
            name='exterior_package',
        ),
        migrations.RemoveField(
            model_name='packages1',
            name='extra_package',
        ),
        migrations.RemoveField(
            model_name='packages1',
            name='interior_package',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='level_one',
        ),
        migrations.RemoveField(
            model_name='packages2',
            name='exterior_package',
        ),
        migrations.RemoveField(
            model_name='packages2',
            name='extra_package',
        ),
        migrations.RemoveField(
            model_name='packages2',
            name='interior_package',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='level_two',
        ),
        migrations.RemoveField(
            model_name='packages3',
            name='exterior_package',
        ),
        migrations.RemoveField(
            model_name='packages3',
            name='extra_package',
        ),
        migrations.RemoveField(
            model_name='packages3',
            name='interior_package',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='level_three',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddField(
            model_name='levels',
            name='engine_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levels',
            name='engine_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levels',
            name='packages',
            field=models.ManyToManyField(to='core1.package'),
        ),
        migrations.DeleteModel(
            name='Packages_1_exterior_Data',
        ),
        migrations.DeleteModel(
            name='Packages_1_extra_Data',
        ),
        migrations.DeleteModel(
            name='Packages_1_interior_Data',
        ),
        migrations.DeleteModel(
            name='Packages1',
        ),
        migrations.DeleteModel(
            name='Packages_2_exterior_Data',
        ),
        migrations.DeleteModel(
            name='Packages_2_extra_Data',
        ),
        migrations.DeleteModel(
            name='Packages_2_interior_Data',
        ),
        migrations.DeleteModel(
            name='Packages2',
        ),
        migrations.DeleteModel(
            name='Packages_3_exterior_Data',
        ),
        migrations.DeleteModel(
            name='Packages_3_extra_Data',
        ),
        migrations.DeleteModel(
            name='Packages_3_interior_Data',
        ),
        migrations.DeleteModel(
            name='Packages3',
        ),
    ]
